<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="BillingProviderServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/BillingProviderServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/BillingProviderServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://rs.udc.es/billing">
    <import location="BillingProviderService.wsdl" namespace="http://rs.udc.es/billing"/>
    <plnk:partnerLinkType name="BillingProviderLinkType">
        <plnk:role name="BillingProviderRole" portType="ns:BillingProvider"/>
    </plnk:partnerLinkType>
</definitions>
