<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="RatingProviderServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/RatingProviderServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/RatingProviderServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://rs.udc.es/rating">
    <import location="RatingProviderService.wsdl" namespace="http://rs.udc.es/rating"/>
    <plnk:partnerLinkType name="RatingProviderLinkType">
        <plnk:role name="RatingProviderRole" portType="ns:RatingProvider"/>
    </plnk:partnerLinkType>
</definitions>
