<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="RewardProviderServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/RewardProviderServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/RewardProviderServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://rs.udc.es/reward">
    <import location="RewardProviderService.wsdl" namespace="http://rs.udc.es/reward"/>
    <plnk:partnerLinkType name="RewardProviderLinkType">
        <plnk:role name="RewardProviderRole" portType="ns:RewardProvider"/>
    </plnk:partnerLinkType>
</definitions>
