<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="WizardCorrelationProperties.wsdl" targetNamespace="http://enterprise.netbeans.org/bpel/WizardCorrelationProperties" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:ns="http://j2ee.netbeans.org/wsdl/FlujoBPEL/src/CallsSearch" xmlns:tns="http://enterprise.netbeans.org/bpel/WizardCorrelationProperties">
    <import namespace="http://j2ee.netbeans.org/wsdl/FlujoBPEL/src/CallsSearch" location="CallsSearch.wsdl"/>
    <vprop:property name="wzrd_prop_long_long" type="xsd:long"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_long_long" messageType="ns:CallsSearchOperationRequest" part="customerID"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_long_long" messageType="ns:SentBillRequest" part="customerID"/>
    <vprop:property name="wzrd_prop_byte_byte" type="xsd:byte"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_byte_byte" messageType="ns:CallsSearchOperationRequest" part="month"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_byte_byte" messageType="ns:SentBillRequest" part="month"/>
    <vprop:property name="wzrd_prop_integer_integer" type="xsd:integer"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_integer_integer" messageType="ns:CallsSearchOperationRequest" part="year"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_integer_integer" messageType="ns:SentBillRequest" part="year"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_byte_byte" messageType="ns:payedBillRequest" part="month"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_integer_integer" messageType="ns:payedBillRequest" part="year"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_long_long" messageType="ns:payedBillRequest" part="customerID"/>
</definitions>
